-- Establish the pre-normalization schema and the audit table.
--
-- The IF NOT EXISTS clauses allow this migration to be applied to the
-- Hibernate-created schema that existed before Flyway was introduced.
CREATE TABLE IF NOT EXISTS software_engineer (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    tech_stack VARCHAR(255),
    aggregate_version INTEGER NOT NULL DEFAULT 0
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'software_engineer'
          AND column_name = 'aggregate_version'
    ) THEN
        ALTER TABLE software_engineer
            ADD COLUMN aggregate_version INTEGER NOT NULL DEFAULT 0;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'software_engineer'
          AND column_name = 'tech_stack'
    ) THEN
        ALTER TABLE software_engineer
            ADD COLUMN tech_stack VARCHAR(255);
    END IF;
END $$;

ALTER TABLE software_engineer
    ALTER COLUMN aggregate_version SET DEFAULT 0;

ALTER TABLE software_engineer
    ALTER COLUMN aggregate_version SET NOT NULL;

ALTER TABLE software_engineer
    ALTER COLUMN name SET NOT NULL;

CREATE TABLE IF NOT EXISTS engineer_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    aggregate_id INTEGER NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    aggregate_version INTEGER NOT NULL,
    schema_version INTEGER NOT NULL,
    payload OID NOT NULL,
    CONSTRAINT uk_engineer_audit_event_id UNIQUE (event_id)
);

CREATE INDEX IF NOT EXISTS idx_engineer_audit_aggregate_version
    ON engineer_audit (aggregate_id, aggregate_version, occurred_at);
