-- Create reusable technology rows and migrate the legacy comma-separated
-- software_engineer.tech_stack values into the join table.
CREATE TABLE IF NOT EXISTS technology (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_technology_normalized_name UNIQUE (normalized_name)
);

CREATE TABLE IF NOT EXISTS software_engineer_technology (
    software_engineer_id INTEGER NOT NULL,
    technology_id INTEGER NOT NULL,
    CONSTRAINT uk_software_engineer_technology
        PRIMARY KEY (software_engineer_id, technology_id),
    CONSTRAINT fk_software_engineer_technology_engineer
        FOREIGN KEY (software_engineer_id) REFERENCES software_engineer (id),
    CONSTRAINT fk_software_engineer_technology_technology
        FOREIGN KEY (technology_id) REFERENCES technology (id)
);

-- Match TechnologyService's canonical representation: trim values, collapse
-- whitespace, compare case-insensitively, and capitalize the first character.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM software_engineer engineer
        CROSS JOIN LATERAL regexp_split_to_table(
            COALESCE(engineer.tech_stack, ''), ','
        ) AS raw(technology_name)
        WHERE btrim(raw.technology_name) <> ''
          AND length(regexp_replace(btrim(raw.technology_name), '\s+', ' ', 'g')) > 100
    ) THEN
        RAISE EXCEPTION
            'Cannot migrate tech_stack value longer than % characters', 100;
    END IF;

    INSERT INTO technology (name, normalized_name)
    SELECT DISTINCT ON (lower(canonical_name))
        canonical_name,
        lower(canonical_name)
    FROM (
        SELECT upper(left(collapsed_name, 1)) || substring(collapsed_name FROM 2)
                   AS canonical_name
        FROM (
            SELECT lower(regexp_replace(btrim(raw.technology_name), '\s+', ' ', 'g'))
                       AS collapsed_name
            FROM software_engineer engineer
            CROSS JOIN LATERAL regexp_split_to_table(
                COALESCE(engineer.tech_stack, ''), ','
            ) AS raw(technology_name)
            WHERE btrim(raw.technology_name) <> ''
        ) collapsed
    ) canonical
    ORDER BY lower(canonical_name), canonical_name
    ON CONFLICT (normalized_name) DO NOTHING;

    INSERT INTO software_engineer_technology (software_engineer_id, technology_id)
    SELECT DISTINCT
        engineer.id,
        technology.id
    FROM software_engineer engineer
    CROSS JOIN LATERAL regexp_split_to_table(
        COALESCE(engineer.tech_stack, ''), ','
    ) AS raw(technology_name)
    JOIN technology
      ON technology.normalized_name = lower(
          upper(left(regexp_replace(btrim(raw.technology_name), '\s+', ' ', 'g'), 1))
          || substring(regexp_replace(btrim(raw.technology_name), '\s+', ' ', 'g') FROM 2)
      )
    WHERE btrim(raw.technology_name) <> ''
    ON CONFLICT (software_engineer_id, technology_id) DO NOTHING;
END $$;
